const ImageData = {
    ar00: require("../../assets/cards/m00.jpg"),
    ar01: require("../../assets/cards/m01.jpg"),
    ar02: require("../../assets/cards/m02.jpg"),
    ar03: require("../../assets/cards/m03.jpg"),
    ar04: require("../../assets/cards/m04.jpg"),
    ar05: require("../../assets/cards/m05.jpg"),
    ar06: require("../../assets/cards/m06.jpg"),
    ar07: require("../../assets/cards/m07.jpg"),
    ar08: require("../../assets/cards/m08.jpg"),
    ar09: require("../../assets/cards/m09.jpg"),
    ar10: require("../../assets/cards/m10.jpg"),
    ar11: require("../../assets/cards/m11.jpg"),
    ar12: require("../../assets/cards/m12.jpg"),
    ar13: require("../../assets/cards/m13.jpg"),
    ar14: require("../../assets/cards/m14.jpg"),
    ar15: require("../../assets/cards/m15.jpg"),
    ar16: require("../../assets/cards/m16.jpg"),
    ar17: require("../../assets/cards/m17.jpg"),
    ar18: require("../../assets/cards/m18.jpg"),
    ar19: require("../../assets/cards/m19.jpg"),
    ar20: require("../../assets/cards/m20.jpg"),
    ar21: require("../../assets/cards/m21.jpg"),
}
export default ImageData